[package]
name = "chorus"
version = "0.1.0"
license = "AGPL-3"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = "1.27.0"
serde = "1.0.159"
serde_json = "1.0.95"
reqwest = "0.11.16"
url = "2.3.1"