[package]
name = "chorus"
version = "0.1.0"
license = "AGPL-3"
edition = "2021"

[dependencies]
tokio = {version = "1.27.0", features = ["rt", "macros", "rt-multi-thread"]}
serde = {version = "1.0.163", features = ["derive"]}
serde_json = {version= "1.0.96", features = ["raw_value"]}
serde-aux = "4.2.0"
reqwest = {version = "0.11.16", features = ["multipart"]}
url = "2.3.1"
chrono = {version = "0.4.24", features = ["serde"]}
regex = "1.7.3"
custom_error = "1.9.2"
native-tls = "0.2.11"
tokio-tungstenite = {version = "0.19.0", features = ["native-tls"]}
futures-util = "0.3.28"
http = "0.2.9"

[dev-dependencies]
lazy_static = "1.4.0"